[package]
name = "guessing-game"
version = "0.1.0"
authors = ["Stuv7CB <olev.l.s43@gmail.com>"]

[dependencies.conrod]
version = "0.58.0"
features = ["glium", "winit"]

[dependencies]
find_folder = "*"
rand = "*"